---
- name: Create directories and subdirectories
  hosts: your_target_host
  become: yes

  vars:
    base_directories:
      - watchtower
      - portainer_agent
      # Add any additional directories here

    subdirectories:
      - build
      - run
      - temp
      # Add any additional subdirectories here

  tasks:
    - name: Create base directories
      file:
        path: "/opt/docker/{{ item }}"
        state: directory
        mode: '0755'
      with_items: "{{ base_directories }}"

    - name: Create subdirectories in base directories
      file:
        path: "/opt/docker/{{ item.0 }}/{{ sub_dir }}"
        state: directory
        mode: '0755'
      loop: "{{ subdirectories }}"
      loop_control:
        loop_var: sub_dir
      with_nested:
        - "{{ base_directories }}"
        - "{{ subdirectories }}"
