---
- name: Create directories, set timezone, and write docker-compose.yml
  hosts: localhost
  become: yes

  vars:
    base_directories:
      - watchtower
      - portainer_agent
      # Add any additional directories here

    subdirectories:
      - build
      - run
      - temp
      # Add any additional subdirectories here

    timezone: Australia/Adelaide  # Set your desired timezone here

    docker_compose_content: |
      version: "3"
      services:
        watchtower:
          image: containrrr/watchtower
          restart: always
          volumes:
            - /etc/localtime:/etc/localtime:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - /etc/timezone:/etc/timezone:ro
          environment:
            - PUID=1000
            - PGID=1000
            - TZ={{ timezone }}
            - UMASK_SET=022 #optional
            - WATCHTOWER_CLEANUP=true
            - WATCHTOWER_LABEL_ENABLE=true
            - WATCHTOWER_INCLUDE_RESTARTING=true
          labels:
            - "com.centurylinklabs.watchtower.enable=true"

  tasks:
    - name: Create directories and subdirectories
      file:
        path: "/opt/docker/{{ item.0 }}/{{ item.1 }}"
        state: directory
        mode: '0755'
      loop: "{{ base_directories | product(subdirectories) | list }}"

    - name: Set timezone
      command: "timedatectl set-timezone {{ timezone }}"
      become: yes

    - name: Write docker-compose.yml
      ansible.builtin.file:
        path: "/opt/docker/watchtower/build/docker-compose.yml"
        state: touch
        mode: '0644'
      ansible.builtin.blockinfile:
        path: "/opt/docker/watchtower/build/docker-compose.yml"
        content: "{{ docker_compose_content }}"
