---
- name: Create directories and subdirectories
  hosts: localhost
  become: yes

  vars:
    base_directories:
      - watchtower
      - portainer_agent
      # Add any additional directories here

    subdirectories:
      - build
      - run
      - temp
      # Add any additional subdirectories here

  tasks:
    - name: Create directories
      file:
        path: "/opt/docker/{{ item.0 }}"
        state: directory
        mode: '0755'
      with_items: "{{ base_directories | product(['']) | list }}"

    - name: Create subdirectories in base directories
      file:
        path: "/opt/docker/{{ item.0 }}/{{ item.1 }}"
        state: directory
        mode: '0755'
      with_items:
        - "{{ base_directories }}"
        - "{{ subdirectories }}"
      when: item.1 != ''
