---
- name: Create directories, set timezone, and write docker-compose.yml
  hosts: localhost
  become: yes

  vars:
    base_directories:
      - watchtower
      - portainer_agent
      # Add any additional directories here

    subdirectories:
      - build
      - run
      - temp
      # Add any additional subdirectories here

    timezone: Australia/Adelaide  # Set your desired timezone here

  tasks:
    - name: Create directories and subdirectories
      file:
        path: "/opt/docker/{{ item.0 }}/{{ item.1 }}"
        state: directory
        mode: '0755'
      loop: "{{ base_directories | product(subdirectories) | list }}"

    - name: Set timezone
      command: "timedatectl set-timezone {{ timezone }}"
      become: yes

    - name: Write docker-compose.yml
      template:
        src: docker-compose.yml.j2
        dest: "/opt/docker/watchtower/build/docker-compose.yml"
      vars:
        timezone: "{{ timezone }}"
