---
- name: Create directories and subdirectories
  hosts: localhost
  become: yes

  vars:
    base_directories:
      - /opt/docker/watchtower
      - /opt/docker/portainer_agent
      # Add any additional directories here

    subdirectories:
      - build
      - run
      - temp
      # Add any additional subdirectories here

  tasks:
    - name: Create base directories
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      with_items: "{{ base_directories }}"

    - name: Create subdirectories in base directories
      file:
        path: "{{ base_dir }}/{{ sub_dir }}"
        state: directory
        mode: '0755'
      loop: "{{ subdirectories }}"
      loop_control:
        loop_var: sub_dir
      with_items: "{{ base_directories }}"
      vars:
        base_dir: "{{ item }}"
