---
- name: Create directories and subdirectories
  hosts: localhost
  become: yes

  vars:
    base_directories:
      - watchtower
      - portainer_agent
      # Add any additional directories here

    subdirectories:
      - build
      - run
      - temp
      # Add any additional subdirectories here

  tasks:
    - name: Create base directories
      file:
        path: "/opt/docker/{{ item }}"
        state: directory
        mode: '0755'
      with_items: "{{ base_directories }}"

    - name: Create subdirectories in base directories
      file:
        path: "/opt/docker/{{ item }}/subdirectory/{{ subdir }}"
        state: directory
        mode: '0755'
      loop: "{{ base_directories }}"
      loop_control:
        loop_var: item
      loop_var: subdir
